### ISSUE TITLE
libFLAC failed compiling, stopping the script

### ISSUE THREAD

**Issue by lapshinji** [jb-alvarado/media-autobuild_suite#264]
` Starting 32bit compilation of audio tools

libilbc git ............................................... [Up-to-date]
opus 1.1.2 ................................................ [Up-to-date]
speex 1.2rc2 .............................................. [Up-to-date]
flac 1.3.1 ............................................. [Not installed]
├ flac-1.3.1 ......................................... [File up-to-date]
├ Running extract...
├ Running configure...
├ Running make...
Likely error:
../../src/libFLAC/.libs/libFLAC.a(stream_encoder.o):stream_encoder.c:(.text+0xbc4c): undefined reference to `FLAC__lpc_compute_autocorrelation_asm_ia32_sse_lag_12'
../../src/libFLAC/.libs/libFLAC.a(stream_encoder.o):stream_encoder.c:(.text+0xbc74): undefined reference to `FLAC__lpc_compute_autocorrelation_asm_ia32'
../../src/libFLAC/.libs/libFLAC.a(stream_encoder.o):stream_encoder.c:(.text+0xbc79): undefined reference to `FLAC__lpc_compute_autocorrelation_asm_ia32_sse_lag_16'
../../src/libFLAC/.libs/libFLAC.a(stream_encoder.o):stream_encoder.c:(.text+0xc200): undefined reference to `fopen_utf8'
../../src/libFLAC/.libs/libFLAC.a(stream_encoder.o):stream_encoder.c:(.text+0xc290): undefined reference to `fopen_utf8'
collect2.exe: error: ld returned 1 exit status
make[3]: *** [flac.exe] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
make failed. Check /build/flac-1.3.1/build-32bit/ab-suite.make.error.log
This is required for other packages, so this script will exit.
`

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/112480/logs.zip)

**Comment by wiiaboo** [comment]
This seems caused by ignoring msys2-runtime, I'm reverting that commit, should be fixed.
