### ISSUE TITLE
[mingw64] [opus-tools] #define OPE_GET_NB_STREAMS(x) OPE_GET_NB_STREAMS_REQUEST, __opus_check_int_ptr(x)

### ISSUE THREAD

**Issue by ahmadrr** [jb-alvarado/media-autobuild_suite#3036]
``` bash
        Warning: We will not accept any issues lacking any form of logs or logs.zip!

        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt

        Starting 64bit compilation of global tools

        Starting 64bit compilation of audio tools
  Running git update for fdk-aac ...
fdk-aac git  ................................................ [Up-to-date]
  Running git update for bin-fdk-aac ...
bin-fdk-aac git  ............................................ [Up-to-date]
  Running git update for opus ...
opus git  ................................................... [Up-to-date]
  Running git update for opusfile ...
opusfile git  ............................................... [Up-to-date]
  Running git update for libopusenc ...
libopusenc git  ............................................. [Up-to-date]
  Running git update for opus-tools ...
┌ opus-tools git  ................................... [Newer dependencies]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
  145 | #define OPE_GET_NB_STREAMS(x) OPE_GET_NB_STREAMS_REQUEST, __opus_check_int_ptr(x)
      |                                                           ^~~~~~~~~~~~~~~~~~~~
../src/opusenc.c:967:30: note: in expansion of macro 'OPE_GET_NB_STREAMS'
  967 |   ret = ope_encoder_ctl(enc, OPE_GET_NB_STREAMS(&data.nb_streams));
      |                              ^~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:881: src/opusenc-opusenc.o] Error 1
make[2]: Leaving directory '/build/opus-tools-git/build-64bit'
make[1]: *** [Makefile:1107: all-recursive] Error 1
make[1]: Leaving directory '/build/opus-tools-git/build-64bit'
make: *** [Makefile:537: all] Error 2
make failed. Check D:/Downloads/mabs/build/opus-tools-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

WARNING: No such file or directory
/trunk/media-autobuild_suite.bat


Attach D:\Downloads\mabs\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```

[logs.zip](https://github.com/user-attachments/files/23670787/logs.zip)

**Comment by Bertaz** [comment]
I get the same error. It compiled without problems a couple of days ago.
``` bash
make[1]: Entering directory '/build/opus-tools-git/build-64bit'
Making all in .
make[2]: Entering directory '/build/opus-tools-git/build-64bit'
  CC       src/opusenc-opus_header.o
  CC       src/opusenc-opusenc.o
In file included from ../src/opusenc.c:71:
../src/opusenc.c: In function 'main':
D:/ffmpegAutobuildSuite/local64/include/opus/opusenc.h:134:63: error: implicit declaration of function '__opus_check_int'; did you mean 'opus_check_int'? [-Wimplicit-function-declaration]
  134 | #define OPE_SET_MUXING_DELAY(x) OPE_SET_MUXING_DELAY_REQUEST, __opus_check_int(x)
      |                                                               ^~~~~~~~~~~~~~~~
../src/opusenc.c:946:30: note: in expansion of macro 'OPE_SET_MUXING_DELAY'
  946 |   ret = ope_encoder_ctl(enc, OPE_SET_MUXING_DELAY(max_ogg_delay));
      |                              ^~~~~~~~~~~~~~~~~~~~
D:/ffmpegAutobuildSuite/local64/include/opus/opusenc.h:134:63: warning: nested extern declaration of '__opus_check_int' [-Wnested-externs]
  134 | #define OPE_SET_MUXING_DELAY(x) OPE_SET_MUXING_DELAY_REQUEST, __opus_check_int(x)
      |                                                               ^~~~~~~~~~~~~~~~
../src/opusenc.c:946:30: note: in expansion of macro 'OPE_SET_MUXING_DELAY'
  946 |   ret = ope_encoder_ctl(enc, OPE_SET_MUXING_DELAY(max_ogg_delay));
      |                              ^~~~~~~~~~~~~~~~~~~~
D:/ffmpegAutobuildSuite/local64/include/opus/opusenc.h:145:59: error: implicit declaration of function '__opus_check_int_ptr'; did you mean 'opus_check_int_ptr'? [-Wimplicit-function-declaration]
  145 | #define OPE_GET_NB_STREAMS(x) OPE_GET_NB_STREAMS_REQUEST, __opus_check_int_ptr(x)
      |                                                           ^~~~~~~~~~~~~~~~~~~~
../src/opusenc.c:967:30: note: in expansion of macro 'OPE_GET_NB_STREAMS'
  967 |   ret = ope_encoder_ctl(enc, OPE_GET_NB_STREAMS(&data.nb_streams));
      |                              ^~~~~~~~~~~~~~~~~~
D:/ffmpegAutobuildSuite/local64/include/opus/opusenc.h:145:59: warning: nested extern declaration of '__opus_check_int_ptr' [-Wnested-externs]
  145 | #define OPE_GET_NB_STREAMS(x) OPE_GET_NB_STREAMS_REQUEST, __opus_check_int_ptr(x)
      |                                                           ^~~~~~~~~~~~~~~~~~~~
../src/opusenc.c:967:30: note: in expansion of macro 'OPE_GET_NB_STREAMS'
  967 |   ret = ope_encoder_ctl(enc, OPE_GET_NB_STREAMS(&data.nb_streams));
      |                              ^~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:881: src/opusenc-opusenc.o] Error 1
make[2]: Leaving directory '/build/opus-tools-git/build-64bit'
make[1]: *** [Makefile:1107: all-recursive] Error 1
make[1]: Leaving directory '/build/opus-tools-git/build-64bit'
make: *** [Makefile:537: all] Error 2
```

[logs.zip](https://github.com/user-attachments/files/23678006/logs.zip)

**Comment by Bertaz** [comment]
Opened PR that will fix https://github.com/xiph/libopusenc/pull/36.

Caused by https://github.com/xiph/opus/commit/7817df7908318fb3a0af2a01e4da1e25643967d0.
Fixed by [0001-Fix-use-of-reserved-identifiers.patch](https://github.com/user-attachments/files/23685020/0001-Fix-use-of-reserved-identifiers.patch) (on [opusenc.h](https://github.com/xiph/libopusenc/blob/e4285b5e8c20a06746f656102c5be8aef83f7ccb/include/opusenc.h#L132)).

**Comment by ycwan** [comment]
@ [Bertaz](https://github.com/Bertaz)

Which folder should I place the fix patch file "**0001-Fix-use-of-reserved-identifiers.patch (on opusenc.h)**" ?

**Comment by basilisk0315** [comment]
Until an official fix, I created this quick-and-dirty script based on the patch file:
```shell
#!/bin/bash

printf '[%s]: start\n' "$(date +'%Y%m%d-%H%M%S')" >opus-tools_extras.out

SRC_FILE="$LOCALDESTDIR"'/include/opus/opusenc.h'
TMP_FILE="$SRC_FILE"'.tmp'

printf '[%s]: SRC_FILE [%s]\n' "$(date +'%Y%m%d-%H%M%S')" "$SRC_FILE" >>opus-tools_extras.out
printf '[%s]: TMP_FILE [%s]\n' "$(date +'%Y%m%d-%H%M%S')" "$TMP_FILE" >>opus-tools_extras.out

sed 's/_REQUEST, __opus/_REQUEST, opus/' "$SRC_FILE" >"$TMP_FILE"
diff -q "$SRC_FILE" "$TMP_FILE" >/dev/null 2>&1
if (( $? != 0 ))
then
	mv "$SRC_FILE" "$SRC_FILE"'.'"$(date +'%Y%m%d.%H%M%S')"
	mv "$TMP_FILE" "$SRC_FILE"
	printf '[%s]: Changed\n' "$(date +'%Y%m%d-%H%M%S')" >>opus-tools_extras.out
else
	rm "$TMP_FILE"
	printf '[%s]: No change\n' "$(date +'%Y%m%d-%H%M%S')" >>opus-tools_extras.out
fi

printf '[%s]: finished\n' "$(date +'%Y%m%d-%H%M%S')" >>opus-tools_extras.out
``` 

If you want to use it save it as `opus-tools_extra.sh` in your `build` directory. Then run the suite.

I hope this helps.

Cheers
John

**Comment by LigH-de** [comment]
> If you want to use it save it as opus-tools_extra.sh in your build directory. Then run the suite.

As of today, it's working well, thanks! 👍

**Comment by L4cache** [comment]
Fixed upstream
